apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fuse7-java-openshift-wom-rest-appdynamics
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: '${APP_NAME}'
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
        vsts/build-version: '${BUILD_VERSION}'    
        vsts/release-number: '${RELEASE_NUMBER}'
      name: '${APP_NAME}'
    spec:
      clusterIP: None
      deprecatedPublicIPs: []
      ports:
        - name: service-rest
          port: 8889
          protocol: TCP
          targetPort: 8889
      selector:
        app: '${APP_NAME}'
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
        vsts/build-version: '${BUILD_VERSION}'    
        vsts/release-number: '${RELEASE_NUMBER}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        app: '${APP_NAME}'
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
        vsts/build-version: '${BUILD_VERSION}'    
        vsts/release-number: '${RELEASE_NUMBER}'
      name: '${APP_NAME}'
    spec:
      replicas: 1
      selector:
        app: '${APP_NAME}'
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
        vsts/build-version: '${BUILD_VERSION}'    
        vsts/release-number: '${RELEASE_NUMBER}'
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: '${APP_NAME}'
            component: '${APP_NAME}'
            group: fuse7-java-openshift
            version: '${APP_VERSION}'
            vsts/build-version: '${BUILD_VERSION}'    
            vsts/release-number: '${RELEASE_NUMBER}'
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: APP_ENV
                  value: '${APP_ENV}'
                - name: APPDYNAMICS_CONTROLLER_HOST_NAME
                  value: '${APPDYNAMICS_CONTROLLER_HOST_NAME}'
                - name: APPDYNAMICS_CONTROLLER_PORT
                  value: '${APPDYNAMICS_CONTROLLER_PORT}'
                - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
                  value: '${APPDYNAMICS_CONTROLLER_SSL_ENABLED}'
                - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
                  value: '${APPDYNAMICS_AGENT_ACCOUNT_NAME}'
                - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
                  value: '${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}'
                - name: APPDYNAMICS_AGENT_APPLICATION_NAME
                  value: '${APPDYNAMICS_AGENT_APPLICATION_NAME}'
                - name: TZ
                  value: '${TZ}'
                - name: APPDYNAMICS_AGENT_TIER_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: APPDYNAMICS_AGENT_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MONGODB_URL
                  value: '${MONGODB_URL}'
                - name: MONGODB_DB
                  value: '${MONGODB_DB}'
              image: 'library/${APP_NAME}:${IMAGE_TAG}'
              livenessProbe:
                initialDelaySeconds: 180
                tcpSocket:
                  port: 8889
              name: '${APP_NAME}'
              ports:
                - containerPort: 8889
                  name: service-rest
              readinessProbe:
                initialDelaySeconds: 20
                tcpSocket:
                  port: 8889
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
                limits:
                  cpu: 500m
                  memory: 400Mi
              volumeMounts:
              - mountPath: /home/node/app/config
                name: volume-properties-file
          volumes:
          - configMap:
              defaultMode: 420
              name: ${APP_NAME}-properties
            name: volume-properties-file
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - '${APP_NAME}'
            from:
              kind: ImageStreamTag
              name: '${APP_NAME}:${IMAGE_TAG}'
          type: ImageChange
    status: {}
parameters:
  - description: The name assigned to the application.
    displayName: Application Name
    name: APP_NAME
    required: true
  - description: The application version.
    displayName: Application Version
    name: APP_VERSION
    required: true
  - description: Properties file path.
    displayName: Properties file
    name: APP_ENV
    required: true
  - description: Image tag that will be used.
    displayName: Image Stream tag
    name: IMAGE_TAG
    required: true
  - description: VSTS Build version.    
    displayName: VSTS Build version   
    name: BUILD_VERSION   
    required: true    
  - description: VSTS Release number.   
    displayName: VSTS Release number    
    name: RELEASE_NUMBER    
    required: true
  - description: AppDynamics Controller Host
    displayName: AppDynamics Controller Host
    name: APPDYNAMICS_CONTROLLER_HOST_NAME
  - description: AppDynamics Controller Port
    displayName: AppDynamics Controller Port
    name: APPDYNAMICS_CONTROLLER_PORT
  - description: AppDyanamics SSL Enabled
    displayName: AppDyanamics SSL Enabled
    name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
  - description: AppDynamics Agent Account Name
    displayName: AppDynamics Agent Account Name
    name: APPDYNAMICS_AGENT_ACCOUNT_NAME
  - description: AppDynamics Agent Acount Key
    displayName: AppDynamics Agent Acount Key
    name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
  - description: AppDyanamics Agent Application Name
    displayName: AppDyanamics Agent Application Name
    name: APPDYNAMICS_AGENT_APPLICATION_NAME
    value: 'OPENSHIFT'    
  - description: Time Zone
    displayName: Time Zone
    name: TZ
    required: true
    value: America/Santiago
  - description: Logs Level
    displayName: Logs Level
    name: LOGLEVEL
    required: true
    value: INFO
  - description: Conexión a mongoDB
    displayName: Conexión a mongoDB
    name: MONGODB_URL
    required: true
  - description: Base de datos mongoDB
    displayName: Base de datos mongoDB
    name: MONGODB_DB
    required: true
